### ISSUE TITLE
model definition in generate_sal.py

### ISSUE THREAD

**Issue by lbl680** [Xiaoqi-Zhao-DLUT/GateNet-RGB-Saliency#11]
The parameters of this model definition
"net = GateNet().cuda()"
are missing.
Could you please provide the parameters?

**Comment by Xiaoqi-Zhao-DLUT** [comment]
@lbl680  The Trained Model always exists  in the  link  [BaiduYunPan(s3l2)](https://pan.baidu.com/s/1-S9fhoCu8fHwi5WKjUCf_g).
