### ISSUE TITLE
Visualize Precision-Recall Curve

### ISSUE THREAD

**Issue by shilpamathew14** [Xiaoqi-Zhao-DLUT/GateNet-RGB-Saliency#12]
First of all, thank you for the wonderful code shared.

I am glad that I could execute it well with all modules implemented. All the evaluation metric values also have been obtained correctly. As found in your paper, I would like to plot the PR curve. Can you kindly share an advise on  plotting the PR curve?

Thank you in advance.

**Comment by Xiaoqi-Zhao-DLUT** [comment]
@shilpamathew14 You also can use the toolkit released by us:https://github.com/lartpang/Py-SOD-VOS-EvalToolkit.

**Comment by shilpamathew14** [comment]
Thank you for your guidance.
