### ISSUE TITLE
Problem in your generate_visfeamaps.py

### ISSUE THREAD

**Issue by wanghaitong-q** [Xiaoqi-Zhao-DLUT/GateNet-RGB-Saliency#13]
Thanks for your sharing.

When I test the model, I have a problem in the second step, which is "run the generate_visfeamaps.py". The code that is "net = RGB_sal().cuda()", what is the "RGB_sal"?  If it is your "GateNet", however, there should be 4 outputs while your GateNet only have one output. Could you please tell you how to deal with it?

**Comment by Xiaoqi-Zhao-DLUT** [comment]
@wanghaitong-q 
The generate_visfeamaps.py is only used to visualize the features, not the final saliency map. For those specific features that  you want to visualize,  you can set the return xx... in the model_GateNet_XX.py
