### ISSUE TITLE
saliency maps

### ISSUE THREAD

**Issue by hongminglin08** [Xiaoqi-Zhao-DLUT/GateNet-RGB-Saliency#2]
Hello, in the RGB SOD you provided, saliency maps of gateNet_resnext101 is incomplete, could you send the complete maps to me? Thank you.

**Comment by Xiaoqi-Zhao-DLUT** [comment]
I checked the uploaded saliency maps. There is no problem. Please give more specfic information.

**Comment by Xiaoqi-Zhao-DLUT** [comment]
> 
> 
> I checked the uploaded saliency maps. There is no problem. Please give more specfic information.

**Comment by hongminglin08** [comment]
But DUTS has only 5,016 images and PASCAL-S has only 845, 3 and 5 are missing respectively,such 460.png in PASCAL-S

 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Xiaoqi-Zhao-DLUT"<notifications@github.com&gt;; 
发送时间: 2020年10月15日(星期四) 中午11:47
收件人: "Xiaoqi-Zhao-DLUT/GateNet-RGB-Saliency"<GateNet-RGB-Saliency@noreply.github.com&gt;; 
抄送: "小可爱"<2663321079@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Xiaoqi-Zhao-DLUT/GateNet-RGB-Saliency] saliency maps (#2)





 
I checked the uploaded saliency maps. There is no problem. Please give more specfic information.

**Comment by Xiaoqi-Zhao-DLUT** [comment]
> 
> But DUTS has only 5,016 images and PASCAL-S has only 845, 3 and 5 are missing respectively,such 460.png in PASCAL-S
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Xiaoqi-Zhao-DLUT"<notifications@github.com&gt;; 发送时间: 2020年10月15日(星期四) 中午11:47 收件人: "Xiaoqi-Zhao-DLUT/GateNet-RGB-Saliency"<GateNet-RGB-Saliency@noreply.github.com&gt;; 抄送: "小可爱"<2663321079@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [Xiaoqi-Zhao-DLUT/GateNet-RGB-Saliency] saliency maps (#2) I checked the uploaded saliency maps. There is no problem. Please give more specfic information. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

You can refer to this reply. https://github.com/lartpang/MINet/issues/3

**Comment by hongminglin08** [comment]
ok, thank you very much.
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Xiaoqi-Zhao-DLUT"<notifications@github.com&gt;; 
发送时间: 2020年10月15日(星期四) 中午1:14
收件人: "Xiaoqi-Zhao-DLUT/GateNet-RGB-Saliency"<GateNet-RGB-Saliency@noreply.github.com&gt;; 
抄送: "小可爱"<2663321079@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Xiaoqi-Zhao-DLUT/GateNet-RGB-Saliency] saliency maps (#2)





  
But DUTS has only 5,016 images and PASCAL-S has only 845, 3 and 5 are missing respectively,such 460.png in PASCAL-S
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Xiaoqi-Zhao-DLUT"<notifications@github.com&gt;; 发送时间: 2020年10月15日(星期四) 中午11:47 收件人: "Xiaoqi-Zhao-DLUT/GateNet-RGB-Saliency"<GateNet-RGB-Saliency@noreply.github.com&gt;; 抄送: "小可爱"<2663321079@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [Xiaoqi-Zhao-DLUT/GateNet-RGB-Saliency] saliency maps (#2) I checked the uploaded saliency maps. There is no problem. Please give more specfic information. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
You can refer to this reply. https://github.com/lartpang/MINet/issues?q=is%3Aissue+is%3Aclosed
