### ISSUE TITLE
I retrain the model, however the prediction map is meaningless map. What mighe be the error?

### ISSUE THREAD

**Issue by peipei2015** [Xiaoqi-Zhao-DLUT/GateNet-RGB-Saliency#3]
A part of the training log:

[iter 99500], [total loss 0.04293],[loss1 0.02237],[loss1 0.02055],[lr 0.0000085085186] 
[iter 99600], [total loss 0.04290],[loss1 0.02238],[loss1 0.02052],[lr 0.0000069635378] 
[iter 99700], [total loss 0.04236],[loss1 0.02209],[loss1 0.02027],[lr 0.0000053791028] 
[iter 99800], [total loss 0.04294],[loss1 0.02237],[loss1 0.02057],[lr 0.0000037400418] 
[iter 99900], [total loss 0.04292],[loss1 0.02237],[loss1 0.02055],[lr 0.0000020132107] 
[iter 100000], [total loss 0.04314],[loss1 0.02248],[loss1 0.02066],[lr 0.0000000316228]

**Comment by Xiaoqi-Zhao-DLUT** [comment]
@peipei2015 I guess you may forget to apply the sigmoid fuction for the prediction.

**Comment by peipei2015** [comment]
You uncomment the sigmoid operation in test code.

**Comment by peipei2015** [comment]
Right, thank you.
