### ISSUE TITLE
When resuming last_iter is 0, why ?

### ISSUE THREAD

**Issue by cmdrootaccess** [Xiaoqi-Zhao-DLUT/GateNet-RGB-Saliency#5]
hello,

i trained the model at first at 50k iterations.
```
[iter 49997], [total loss 0.03742],[loss1 0.01920],[loss1 0.01822],[lr 0.0000002054854] 
[iter 49998], [total loss 0.03780],[loss1 0.01941],[loss1 0.01839],[lr 0.0000001586120] 
[iter 49999], [total loss 0.03794],[loss1 0.01949],[loss1 0.01845],[lr 0.0000001101169] 
[iter 50000], [total loss 0.03843],[loss1 0.01973],[loss1 0.01870],[lr 0.0000000590102] 
```
i have resumed training it to reach 100k iterations but in the logs it starts at 0 iterations.
```
{'iter_num': 100000, 'train_batch_size': 4, 'last_iter': 0, 'lr': 0.001, 'lr_decay': 0.9, 'weight_decay': 0.0005, 'momentum': 0.9, 'snapshot': '50000'}

[iter 1], [total loss 0.04253],[loss1 0.02118],[loss1 0.02136],[lr 0.0010000000000] 
```

isnt it supposed to start at 50k going up ? or i can just reduce my iter_num to be 50k again ? 

what do you advice ?

**Comment by Xiaoqi-Zhao-DLUT** [comment]
@cmdrootaccess 
args = {
    'iter_num': 100000,
    'train_batch_size': 4,
    'last_iter': 0,
    'lr': 1e-3,
    'lr_decay': 0.9,
    'weight_decay': 0.0005,
    'momentum': 0.9,
    'snapshot': ''
}  You should set   'last_iter': to 50000  :flushed:

**Comment by cmdrootaccess** [comment]
alright thanks will do that.
