### ISSUE TITLE
Inaccessible BaiduYunPan url

### ISSUE THREAD

**Issue by XuYunqiu** [Xiaoqi-Zhao-DLUT/GateNet-RGB-Saliency#8]
Hi, thanks for sharing your implementations and results.
But I find the url for RGB-D SOD results is inaccessible now.
Would you mind share it again?

**Comment by Xiaoqi-Zhao-DLUT** [comment]
@XuYunqiu We have provided a link to Google Drive where you can download these maps.

**Comment by XuYunqiu** [comment]
Thanks a lot
