### ISSUE TITLE
generate_sal problem

### ISSUE THREAD

**Issue by zxp6329** [Xiaoqi-Zhao-DLUT/GateNet-RGB-Saliency#9]
hello!
     I want to know what's the meaning of the ckpt_path and exp_name in the generate_sal.py. how to define it?
    
![image](https://user-images.githubusercontent.com/49719853/121661087-6ae2e980-cad6-11eb-8db8-8773efa12e40.png)

**Comment by Xiaoqi-Zhao-DLUT** [comment]
@zxp6329  You can keep the settings consistent with train.py
